{
 "title": "Connections",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "asset",
    "label": "Asset",
    "query": "select ip_address \nfrom assets\ngroup by ip_address"
   }
  ]
 },
 "panels": [
  {
   "title": "Group by Source IP",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  source_ip,\n  count(source_ip) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nGROUP BY source_ip",
     "rawQueryText": "SELECT\n  source_ip,\n  count(source_ip) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nGROUP BY source_ip",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Group by Destination IP",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  destination_ip,\n  count(destination_ip) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN (1732425863416 / 1000) AND (1732447463416 / 1000)\n  and source_ip in ('192.168.57.1','192.168.57.2','192.168.57.27')\nGROUP BY destination_ip",
     "rawQueryText": "SELECT\n  destination_ip,\n  count(destination_ip) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nGROUP BY destination_ip",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Group by Application",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  application,\n  count(application) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nGROUP BY application",
     "rawQueryText": "SELECT\n  application,\n  count(application) as metric\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nGROUP BY application",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TOTAL CONNECTIONS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(id) as value\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN (1732425863416 / 1000) AND (1732447463416 / 1000)\n  and source_ip in ('192.168.57.1')",
     "rawQueryText": "SELECT count(id) as value\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%d %H:%M:%S', datetime, 'localtime') AS local_datetime,\n  source_ip,\n  source_port,\n  destination_ip,\n  destination_port,\n  application\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nORDER BY datetime DESC;\n",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%d %H:%M:%S', datetime, 'localtime') AS local_datetime,\n  source_ip,\n  source_port,\n  destination_ip,\n  destination_port,\n  application\nFROM connections\nWHERE\n  unixepoch(datetime) BETWEEN ($__from / 1000) AND ($__to / 1000)\n  and source_ip in (${asset:sqlstring})\nORDER BY datetime DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Active Assets",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "queryText": "SELECT\n  ip_address,\n  mac_address,\n  hostname,\n  os_name,\n  datetime(last_seen_at) as last_seen_at\nFROM assets\nWHERE unixepoch(last_seen_at) BETWEEN (1732425863416 / 1000) AND (1732447463416 / 1000)\nORDER BY last_seen_at DESC;\n",
     "rawQueryText": "SELECT\n  ip_address,\n  mac_address,\n  hostname,\n  os_name,\n  datetime(last_seen_at) as last_seen_at\nFROM assets\nWHERE unixepoch(last_seen_at) BETWEEN ($__from / 1000) AND ($__to / 1000)\nORDER BY last_seen_at DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}